name: Build and Deploy to Server
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          echo $SSH_KEY
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      # - name: Stop the server
      #   run: ssh production 'sudo systemctl stop my-application'

      # - name: Check out the source
      #   run: ssh production 'cd my-application && git fetch && git reset --hard origin/master'
 
      - name: Start the server
        if: ${{ always() }}
        run: ssh production 'docker restart rankme-front'